const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createBackend}=require('./backend-harness.cjs');
const payload=(extra={})=>({name:'Sample Customer',phone:'9000000000',vehicle:'Hyundai i20',date:'2030-01-10',time:'10:00',issue:'Brake noise',requestId:crypto.randomUUID(),...extra});
function book(b,p){return b.post('publicBooking',{payload:p},null)}
function checked(b){const a=book(b,payload()).data;return b.post('checkInService',{payload:{appointmentId:a.appointmentId,name:'Sample Customer',phone:'9000000000',registration:'KA 01 AB 1234',make:'Hyundai',model:'i20',odometer:48000,complaint:'Brake noise'}}).data.job;}
const line=(extra={})=>({line_type:'Part',description:'Brake Cleaner',quantity:2,unit:'can',unit_cost:100,rate:200,...extra});
function bill(b,j,extra={}){return b.post('saveBill',{payload:{jobId:j.id,lines:[line()],payment:'UPI',serviceDate:'2030-01-10',...extra}})}
test('all shipped JavaScript and Apps Script parses',()=>{for(const dir of ['','lib','apps-script'])for(const f of fs.readdirSync(path.join(__dirname,'..',dir)).filter(f=>/\.(js|gs)$/.test(f)))new vm.Script(fs.readFileSync(path.join(__dirname,'..',dir,f),'utf8'),{filename:f})});
test('six equal windows; backend availability exposes no customer data',()=>{const b=createBackend(),r=b.post('slotAvailability',{payload:{date:'2030-01-10'}},null);assert.deepEqual(r.data.slots,['10:00','11:20','12:40','14:00','15:20','16:40']);assert.equal(r.data.dailyCapacity,6);assert.equal(JSON.stringify(r).includes('customers'),false)});
test('all mandatory public fields enforced with no writes',()=>{for(const k of ['name','phone','vehicle','date','time','issue']){const b=createBackend(),r=book(b,payload({[k]:' '}));assert.equal(r.ok,false,k);assert.equal(b.tables.Appointments.length,0);assert.equal(b.tables.Customers.length,0)}});
test('optional email accepted and stored; malformed email rejected',()=>{const b=createBackend();assert.equal(book(b,payload({email:'person@example.test'})).ok,true);assert.equal(b.tables.Customers[0].email,'person@example.test');assert.equal(book(b,payload({time:'11:20',email:'bad'})).ok,false);assert.equal(book(b,payload({time:'11:20',email:''})).ok,true);assert.equal(b.tables.Customers[0].email,'person@example.test')});
test('date and time validation rejects invalid, past and off-grid values',()=>{const b=createBackend();for(const date of ['2030-02-30','2000-01-01','not-date'])assert.equal(book(b,payload({date})).ok,false);for(const time of ['18:00','09:00','10:30'])assert.equal(book(b,payload({time})).ok,false)});
test('two requests for one slot: first succeeds, second conflicts, one appointment',async()=>{const b=createBackend();const r=await Promise.all([Promise.resolve().then(()=>book(b,payload())),Promise.resolve().then(()=>book(b,payload({phone:'9000000001'})))]);assert.equal(r.filter(r=>r.ok).length,1);assert.equal(r[1].code,'SLOT_UNAVAILABLE');assert.equal(b.tables.Appointments.length,1);assert.equal(b.locked,false);assert.ok(b.flushes>=2)});
test('retry request ID returns same booking with no duplicates',()=>{const b=createBackend(),p=payload();const one=book(b,p),two=book(b,p);assert.equal(one.data.appointmentId,two.data.appointmentId);assert.equal(b.tables.Appointments.length,1);assert.equal(b.tables.Vehicles.length,1)});
test('staff insertion also rejects an occupied slot',()=>{const b=createBackend();book(b,payload());const a=b.tables.Appointments[0];const r=b.post('insert',{table:'appointments',row:{...a,id:undefined}});assert.equal(r.code,'SLOT_UNAVAILABLE')});
test('cancellation retains record, reason and audit, releases slot',()=>{const b=createBackend(),a=book(b,payload()).data;assert.equal(b.post('slotAvailability',{payload:{date:'2030-01-10'}},null).data.slots.includes('10:00'),false);const r=b.post('cancelAppointment',{id:a.appointmentId,reason:'Customer changed plans'});assert.equal(r.ok,true);assert.equal(r.data.status,'Cancelled');assert.equal(r.data.cancelled_by,'staff');assert.ok(r.data.cancelled_at);assert.equal(b.tables.Audit_Log[0].action,'cancel_appointment');assert.equal(b.tables.Appointments.length,1);assert.equal(b.post('slotAvailability',{payload:{date:'2030-01-10'}},null).data.slots.includes('10:00'),true);assert.equal(book(b,payload()).ok,true)});
test('cancellation requires auth and workshop ownership',()=>{const b=createBackend(),a=book(b,payload()).data;assert.equal(b.post('cancelAppointment',{id:a.appointmentId},null).code,'AUTH_REQUIRED');assert.equal(b.post('cancelAppointment',{id:a.appointmentId},'foreign-session').ok,false)});
test('cancellation audit failure does not release the slot',()=>{const b=createBackend(),a=book(b,payload()).data;b.failNext('append','Audit_Log');assert.equal(b.post('cancelAppointment',{id:a.appointmentId}).ok,false);assert.equal(b.tables.Appointments[0].status,'Booked')});
test('cancelled appointments cannot be inspected and checked-in appointments cannot be cancelled',()=>{const b=createBackend(),j=checked(b);assert.equal(b.post('cancelAppointment',{id:j.appointment_id}).ok,false);const a=book(b,payload({time:'11:20'})).data;b.post('cancelAppointment',{id:a.appointmentId});assert.equal(b.post('checkInService',{payload:{appointmentId:a.appointmentId,name:'A',phone:'B',registration:'C'}}).ok,false)});
test('legacy off-grid bookings block their containing window; completed slots stay reserved',()=>{const b=createBackend();b.tables.Appointments.push({id:'legacy',workshop_id:'w',preferred_date:'2030-01-10',preferred_time:'10:30',status:'Completed'});assert.equal(b.post('slotAvailability',{payload:{date:'2030-01-10'}},null).data.slots.includes('10:00'),false)});
test('public slot checks cannot bypass staff update/delete restrictions',()=>{const b=createBackend(),a=book(b,payload()).data;assert.equal(b.post('remove',{table:'appointments',id:a.appointmentId}).ok,false);assert.equal(b.post('update',{table:'appointments',id:a.appointmentId,patch:{status:'Cancelled'}}).ok,false)});
test('invoice creates stock master, closes job, saves history, keeps work list',()=>{const b=createBackend(),j=checked(b);b.post('update',{table:'service_jobs',id:j.id,patch:{inspection_notes:'Noise',work_to_be_done:'Clean brakes\nRoad test'}});const r=bill(b,j);assert.equal(r.ok,true,r.error);assert.equal(r.data.job.status,'Closed');assert.equal(r.data.job.work_to_be_done,'Clean brakes\nRoad test');assert.equal(r.data.invoice.total,400);assert.equal(r.data.inventory_items[0].unit,'can');assert.equal(r.data.inventory_items[0].cost,100);assert.equal(r.data.stock_movements[0].quantity,-2);assert.equal(b.tables.Service_History.length,1);assert.equal(b.tables.Reminders.length,0);assert.equal(b.tables.Appointments[0].status,'Completed')});
test('same normalized name reuses one item across invoice lines and preserves tags',()=>{const b=createBackend(),j=checked(b);b.tables.Inventory_Items.push({id:'existing',workshop_id:'w',name:'Brake Cleaner',unit:'can',on_hand:10,cost:75,selling_price:180,compatibility_tags:'Hyundai i20',universal:false,active:true});const r=bill(b,j,{lines:[line({description:' brake   cleaner ',unit_cost:''}),line({line_type:'Consumable',description:'BRAKE CLEANER',unit_cost:'',rate:220})]});assert.equal(r.ok,true,r.error);assert.equal(b.tables.Inventory_Items.length,1);const i=b.tables.Inventory_Items[0];assert.equal(i.on_hand,6);assert.equal(i.cost,75);assert.equal(i.selling_price,220);assert.equal(i.compatibility_tags,'Hyundai i20')});
test('new repeated parts produce a single master; labour and other never do',()=>{const b=createBackend(),j=checked(b),r=bill(b,j,{lines:[line(),line({description:' brake cleaner '}),line({line_type:'Labour',description:'Labour'}),line({line_type:'Other',description:'Disposal'})]});assert.equal(r.ok,true,r.error);assert.equal(b.tables.Inventory_Items.length,1);assert.equal(b.tables.Stock_Movements.length,2)});
test('matching master with incompatible UOM rejected without side effects',()=>{const b=createBackend(),j=checked(b);b.tables.Inventory_Items.push({id:'i',workshop_id:'w',name:'Brake Cleaner',unit:'L',on_hand:5});assert.equal(bill(b,j).ok,false);assert.equal(b.tables.Inventory_Items[0].on_hand,5);assert.equal(b.tables.Invoices.length,0)});
test('invalid foreign master / amounts fail before any bill writes',()=>{for(const lines of [[line({inventory_item_id:'foreign'})],[line({rate:-1})],[line({quantity:0})],[line({unit_cost:-10})]]){const b=createBackend(),j=checked(b);assert.equal(bill(b,j,{lines}).ok,false);assert.equal(b.tables.Invoices.length,0);assert.equal(b.tables.Inventory_Items.length,0)}});
test('invoice retry is idempotent and closed job cannot be reopened',()=>{const b=createBackend(),j=checked(b),a=bill(b,j),r=bill(b,j);assert.equal(a.data.invoice.id,r.data.invoice.id);assert.equal(b.tables.Stock_Movements.length,1);assert.equal(b.tables.Service_History.length,1);assert.equal(b.post('update',{table:'service_jobs',id:j.id,patch:{status:'Open',inspection_notes:'New'}}).ok,false);assert.equal(b.post('replaceJobLines',{jobId:j.id,lines:[]}).ok,false)});
test('storage failure rolls back invoice effects and permits clean retry',()=>{for(const table of ['Stock_Movements','Service_History','Invoices','Audit_Log']){const b=createBackend(),j=checked(b);b.failNext('append',table);const r=bill(b,j);assert.equal(r.ok,false,table);assert.equal(b.tables.Invoices.length,0);assert.equal(b.tables.Inventory_Items.length,0);assert.equal(b.tables.Stock_Movements.length,0);assert.equal(b.tables.Service_History.length,0);assert.equal(b.tables.Service_Jobs[0].status,'Open');assert.equal(bill(b,j).ok,true)}});
test('loadAll and unsupported routes do not access legacy Reminders',()=>{const b=createBackend();delete b.tables.Reminders;assert.equal(b.post('loadAll').ok,true);assert.equal(b.post('loadAll').data.reminders,undefined);assert.equal(b.post('insert',{table:'reminders',row:{}}).ok,false)});
test('Sheet-native dates and times preserve workshop-local values',()=>{const b=createBackend();b.context.spreadsheet_=()=>({getSpreadsheetTimeZone:()=> 'Asia/Kolkata'});assert.equal(b.context.sheetValue_('preferred_date',new Date('2030-01-09T18:30:00Z')),'2030-01-10');assert.equal(b.context.sheetValue_('preferred_time',new Date('2030-01-10T04:30:00Z')),'10:00')});
test('invoice without generating an optional job card still closes correctly',()=>{const b=createBackend(),j=checked(b);assert.equal(j.job_card_generated,false);assert.equal(bill(b,j).data.job.status,'Closed')});
