(function(){
  const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
  const date=d=>String(d||'').slice(0,10);
  function header(w,type,no,when){return `<header class="document-header"><div class="document-identity"><span class="document-logo">ACS<span>CARE • SERVICE • TRUST</span></span><div><h2>${e(w.name||'Arupreet Car Service')}</h2><p>${e(w.address||'Electronic City, Bengaluru')}</p><p>Phone: ${e(w.phone||'+91 99998 27339')}</p></div></div><div class="document-reference"><span>${e(type)}</span><strong>${e(no)}</strong><p>${e(date(when))}</p></div></header>`;}
  function parties(c,v,j){return `<div class="document-parties"><section><h3>Customer</h3><strong>${e(c.name)}</strong><p>${e(c.phone)}</p>${c.email?`<p>${e(c.email)}</p>`:''}</section><section><h3>Vehicle</h3><strong>${e(v.registration)}</strong><p>${e(v.make)} ${e(v.model)} ${e(v.variant||'')}</p><p>Odometer <b>${Number(j.odometer_km||0).toLocaleString('en-IN')} km</b></p></section></div>`;}
  function tasks(j){return String(j.work_to_be_done||j.inspection_notes||j.complaint||'').split(/\r?\n|;/).map(x=>x.trim().replace(/^\d+[.)]\s*/, '')).filter(Boolean);}
  function jobCard(w,j,c,v){const work=tasks(j);return `<article class="service-document">${header(w,'JOB CARD','#'+(j.job_no||j.id||''),j.job_card_created_at||j.check_in_at)}<div class="document-meta"><span>Job No. <b>${e(j.job_no||j.id)}</b></span><span>Status <b>${e(['Closed','Completed'].includes(j.status)?'Closed':j.status||'Open')}</b></span><span>Bay <b>${e(j.bay||'—')}</b></span></div>${parties(c,v,j)}<section class="document-note"><h3>Customer request</h3><p>${e(j.complaint||'—')}</p></section><h3 class="document-section-title">Work to be done</h3><table class="document-table work-table"><thead><tr><th scope="col">No.</th><th scope="col">Work description</th><th scope="col">Done</th></tr></thead><tbody>${work.map((t,i)=>`<tr><td>${i+1}</td><td>${e(t)}</td><td>□</td></tr>`).join('')||'<tr><td>—</td><td>Work to be recorded after inspection.</td><td></td></tr>'}</tbody></table><section class="document-note"><h3>Inspection findings</h3><p>${e(j.inspection_notes||'—')}</p></section><div class="document-signatures"><span>Technician / work notes</span><span>Service advisor</span></div><footer class="document-footer">${e(w.name||'Arupreet Car Service')} · Job #${e(j.job_no||j.id)}<span>Care for your car. Clarity for you.</span></footer></article>`;}
  function invoice(w,i,j,c,v,lines){return `<article class="service-document">${header(w,'INVOICE','#'+(i.invoice_no||i.id||''),i.created_at)}<div class="document-meta"><span>Job No. <b>${e(j.job_no||i.job_id||'—')}</b></span><span>Payment <b>${e(i.payment_status||'')}</b></span><span>Method <b>${e(i.payment_method||'—')}</b></span></div>${parties(c,v,j)}<h3 class="document-section-title">Service & items</h3><table class="document-table invoice-table"><thead><tr><th>No.</th><th>Description</th><th>Qty / UOM</th><th class="number">Rate</th><th class="number">Amount</th></tr></thead><tbody>${lines.map((l,n)=>`<tr><td>${n+1}</td><td>${e(l.description)}<small>${e(l.line_type)}</small></td><td>${e(l.quantity)} ${e(l.unit||'')}</td><td class="number">${money(l.rate)}</td><td class="number">${money(Number(l.quantity)*Number(l.rate))}</td></tr>`).join('')}</tbody></table><div class="document-totals"><p><span>Subtotal</span><b>${money(i.subtotal)}</b></p><p><span>Discount</span><b>− ${money(i.discount)}</b></p><p><span>Tax</span><b>${money(i.tax)}</b></p><p class="total"><span>Total</span><b>${money(i.total)}</b></p></div><div class="document-signatures"><span>Thank you for choosing ACS.</span><span>For ${e(w.name||'Arupreet Car Service')}</span></div><footer class="document-footer">Invoice #${e(i.invoice_no||i.id)} · Job #${e(j.job_no||i.job_id)}<span>Service saved in your vehicle history.</span></footer></article>`;}
  const actions=()=>'<div class="modal-actions"><button class="btn ghost" onclick="closeModal()">Close</button><button class="btn dark" onclick="window.print()">Print / Save PDF</button></div>';
  window.ACSDocuments={jobCard,invoice,actions};
})();
